### ISSUE TITLE
Generate github.io website and populate content

### ISSUE THREAD

**Issue by Mackarous** [Mackarous/ExpandableImageView#11]

**Comment by Mackarous** [comment]
stubbed at http://mackarous.github.io/ExpandableImageView

**Comment by Mackarous** [comment]
We should figure out what to name the "organization" so that my name isn't in the link

**Comment by Mackarous** [comment]
@a-mehta @DeanoDee

**Comment by DeanoDee** [comment]
awesome you got the stub in
